
// This file has been generated by the GUI designer. Do not modify.
namespace KegeratorUI
{
	public partial class PinSettings
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Entry ent_Flow;
		
		private global::Gtk.Entry ent_Temperature;
		
		private global::Gtk.ComboBox cmb_Pins;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Image img_PinLayout;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KegeratorUI.PinSettings
			this.Name = "KegeratorUI.PinSettings";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child KegeratorUI.PinSettings.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 300;
			this.fixed1.HeightRequest = 135;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.ent_Flow = new global::Gtk.Entry ();
			this.ent_Flow.CanFocus = true;
			this.ent_Flow.Name = "ent_Flow";
			this.ent_Flow.IsEditable = true;
			this.ent_Flow.InvisibleChar = '●';
			this.vbox4.Add (this.ent_Flow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.ent_Flow]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.ent_Temperature = new global::Gtk.Entry ();
			this.ent_Temperature.CanFocus = true;
			this.ent_Temperature.Name = "ent_Temperature";
			this.ent_Temperature.IsEditable = true;
			this.ent_Temperature.InvisibleChar = '●';
			this.vbox4.Add (this.ent_Temperature);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.ent_Temperature]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.cmb_Pins = global::Gtk.ComboBox.NewText ();
			this.cmb_Pins.Name = "cmb_Pins";
			this.vbox4.Add (this.cmb_Pins);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.cmb_Pins]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.fixed1.Add (this.vbox4);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.vbox4]));
			w5.X = 142;
			w5.Y = 6;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 15;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Flow Sensor Pin");
			this.vbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Temperature Sensor Pin");
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
			this.vbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label6]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.fixed1.Add (this.vbox3);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.vbox3]));
			w9.X = 5;
			w9.Y = 14;
			w1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.img_PinLayout = new global::Gtk.Image ();
			this.img_PinLayout.Name = "img_PinLayout";
			this.img_PinLayout.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("KegeratorUI.RPiPins.png");
			w1.Add (this.img_PinLayout);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.img_PinLayout]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Internal child KegeratorUI.PinSettings.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonOk]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 551;
			this.DefaultHeight = 835;
			this.Show ();
			this.ent_Temperature.EditingDone += new global::System.EventHandler (this.OnEntTemperatureEditingDone);
		}
	}
}
