
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label lbl_UpperTemp;
	
	private global::Gtk.SpinButton spn_OnTemp;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label lbl_OffTemp;
	
	private global::Gtk.SpinButton spn_OffTemp;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label lbl_BeerLeft;
	
	private global::Gtk.Label lbl_BeerPouredTotal;
	
	private global::Gtk.Label lbl_BeerPouredInstance;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Image img_Beer;
	
	private global::Gtk.Label GtkLabel2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lbl_UpperTemp = new global::Gtk.Label ();
		this.lbl_UpperTemp.Name = "lbl_UpperTemp";
		this.lbl_UpperTemp.LabelProp = global::Mono.Unix.Catalog.GetString ("Fridge On Temperature");
		this.hbox1.Add (this.lbl_UpperTemp);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lbl_UpperTemp]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.spn_OnTemp = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spn_OnTemp.CanFocus = true;
		this.spn_OnTemp.Name = "spn_OnTemp";
		this.spn_OnTemp.Adjustment.PageIncrement = 10D;
		this.spn_OnTemp.ClimbRate = 1D;
		this.spn_OnTemp.Numeric = true;
		this.hbox1.Add (this.spn_OnTemp);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.spn_OnTemp]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lbl_OffTemp = new global::Gtk.Label ();
		this.lbl_OffTemp.Name = "lbl_OffTemp";
		this.lbl_OffTemp.LabelProp = global::Mono.Unix.Catalog.GetString ("Fridge Off Temperature");
		this.hbox2.Add (this.lbl_OffTemp);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lbl_OffTemp]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.spn_OffTemp = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spn_OffTemp.CanFocus = true;
		this.spn_OffTemp.Name = "spn_OffTemp";
		this.spn_OffTemp.Adjustment.PageIncrement = 10D;
		this.spn_OffTemp.ClimbRate = 1D;
		this.spn_OffTemp.Numeric = true;
		this.hbox2.Add (this.spn_OffTemp);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spn_OffTemp]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.fixed2.Add (this.vbox1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.vbox1]));
		w8.X = 7;
		w8.Y = 48;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Homogeneous = true;
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lbl_BeerLeft = new global::Gtk.Label ();
		this.lbl_BeerLeft.Name = "lbl_BeerLeft";
		this.lbl_BeerLeft.Xalign = 0F;
		this.lbl_BeerLeft.LabelProp = global::Mono.Unix.Catalog.GetString ("Beer Left: ");
		this.vbox3.Add (this.lbl_BeerLeft);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lbl_BeerLeft]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lbl_BeerPouredTotal = new global::Gtk.Label ();
		this.lbl_BeerPouredTotal.Name = "lbl_BeerPouredTotal";
		this.lbl_BeerPouredTotal.Xalign = 0F;
		this.lbl_BeerPouredTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total Beer Poured:");
		this.vbox3.Add (this.lbl_BeerPouredTotal);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lbl_BeerPouredTotal]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lbl_BeerPouredInstance = new global::Gtk.Label ();
		this.lbl_BeerPouredInstance.Name = "lbl_BeerPouredInstance";
		this.lbl_BeerPouredInstance.Xalign = 0F;
		this.lbl_BeerPouredInstance.LabelProp = global::Mono.Unix.Catalog.GetString ("Beer Just Poured:");
		this.vbox3.Add (this.lbl_BeerPouredInstance);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lbl_BeerPouredInstance]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.fixed2.Add (this.vbox3);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.vbox3]));
		w12.X = 241;
		w12.Y = 44;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'FileAction\' action=\'FileAction\'><menuite" +
		"m name=\'ExitAction\' action=\'ExitAction\'/></menu><menu name=\'EditAction\' action=\'" +
		"EditAction\'><menuitem name=\'SettingsAction\' action=\'SettingsAction\'/></menu></me" +
		"nubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.fixed2.Add (this.menubar1);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.menubar1]));
		w13.X = 6;
		w13.Y = 9;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.img_Beer = new global::Gtk.Image ();
		this.img_Beer.Name = "img_Beer";
		this.fixed2.Add (this.img_Beer);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.img_Beer]));
		w14.X = 398;
		w14.Y = 37;
		this.GtkAlignment.Add (this.fixed2);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 646;
		this.DefaultHeight = 463;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SettingsAction.Activated += new global::System.EventHandler (this.OnSettingsActionActivated);
		this.spn_OnTemp.ValueChanged += new global::System.EventHandler (this.OnSpnOnTempValueChanged);
		this.spn_OffTemp.ValueChanged += new global::System.EventHandler (this.OnSpnOffTempValueChanged);
	}
}
